# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tarball of all directories
        run: tar -cvf site_content.tar pages styles scripts images

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-content
          path: site_content.tar

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
